version: '3.3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: ceres-back/server:latest
    ports:
      - "8081:8081"
    stdin_open: true  # -i
    tty: true         # -t

