export const RECEIVED_DB_LIST_SUCCESS = 'RECEIVED_DB_LIST_SUCCESS';
export const RECEIVED_DB_LIST_FAILURE = 'RECEIVED_DB_LIST_FAILURE';
export const RECEIVED_USER_PDT_LIST_SUCCESS = 'RECEIVED_USER_PDT_LIST_SUCCESS';
export const RECEIVED_USER_PDT_LIST_FAILURE = 'RECEIVED_USER_PDT_LIST_FAILURE';
