export const RECEIVED_RECIPES_SUCCESS = 'RECEIVED_RECIPES_SUCCESS';
export const RECEIVED_RECIPES_FAILURE = 'RECEIVED_RECIPES_FAILURE';
export const RECEIVED_RECIPES_TAGS_SUCCESS = 'RECEIVED_RECIPES_TAGS_SUCCESS';
export const RECEIVED_RECIPES_TAGS_FAILURE = 'RECEIVED_RECIPES_TAGS_FAILURE';
export const REMOVE_RECIPE = 'REMOVE_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
