export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const LOAD_SHOPPING_LIST = 'LOAD_SHOPPING_LIST';
export const LOAD_SHOPPING_LIST_SUCCESS = 'LOAD_SHOPPING_LIST_SUCCESS';
