export const CHANGE_SHOPPING_ITEM_QUANTITY = 'CHANGE_SHOPPING_ITEM_QUANTITY';
export const CHANGE_SHOPPING_ITEM_COMMENT = 'CHANGE_SHOPPING_ITEM_COMMENT';
export const RECEIVED_SHOPPING_LIST_SUCCESS = 'RECEIVED_SHOPPING_LIST_SUCCESS';
export const RECEIVED_SHOPPING_LIST_FAILURE = 'RECEIVED_SHOPPING_LIST_FAILURE';
export const SAVE_SHOPPING_LIST_FAILURE = 'SAVE_SHOPPING_LIST_FAILURE';
export const ADD_ITEM = 'ADD_ITEM';
