export const CHANGE_STORE_ITEM_QUANTITY = 'CHANGE_STORE_ITEM_QUANTITY';
export const RECEIVED_STORE_SUCCESS = 'RECEIVED_STORE_SUCCESS';
export const RECEIVED_STORE_FAILURE = 'RECEIVED_STORE_FAILURE';
export const UPDATE_STORE_ITEM_FAILURE = 'UPDATE_STORE_ITEM_FAILURE';
export const POST_STORE_ITEM_FAILURE = 'POST_STORE_ITEM_FAILURE';
export const ADD_STORE_ITEM = 'ADD_STORE_ITEM';
export const CREATE_NEW_STORE = 'CREATE_NEW_STORE';
